# Generated by Django 5.1.3 on 2024-11-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=180)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_username', models.CharField(default='', max_length=15)),
                ('usuario_nome', models.CharField(default='', max_length=20)),
                ('usuario_sobrenome', models.EmailField(default='', max_length=20)),
                ('usuario_senha', models.CharField(default='', max_length=30)),
                ('usuario_idade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cadastro de Usuário',
                'verbose_name_plural': 'Cadastro de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_motivo', models.TextField(default='', max_length=100)),
                ('Report_criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to='aplic.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_biografia', models.TextField(default='', max_length=150)),
                ('perfil_interesses', models.CharField(default='', max_length=50)),
                ('perfil_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_conteudo', models.TextField()),
                ('comentario_data_criacao', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aplic.posts')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.usuario')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
